--[[
  cnam-thesis.lua — Lua filter for the cnam-thesis extension

  Automatically injects LaTeX navigation commands for each level-1 chapter,
  so users do not need to write raw {=latex} blocks:

    Unnumbered chapter {.unnumbered}:
      → \phantomsection
         \addcontentsline{toc}{chapter|frontchap}{Title}
         \adjustmtc
         \markboth{\MakeUppercase{Title}}{}

    Numbered chapter:
      → \minitoc
         \newpage   (if minitoc-newpage: true in _quarto.yml)

  Handles short-title="…" at all heading levels:
    Pandoc 3.x ignores this attribute in its LaTeX output. This filter manually
    generates \chapter[short]{long}, \section[short]{long}, etc. so that the
    TOC and running headers display the short title.
    Unnumbered chapters (\chapter*) use short-title in \addcontentsline and \markboth.

  In HTML output these injections are skipped (FORMAT ~= "latex").

  Excluded cases:
    - Empty-title chapters (stub generated by Quarto for index.qmd)
    - Synthetic book section headers generated by Quarto for "Annexes" /
      "Appendices" — Quarto already handles their TOC entry via
      \addcontentsline{toc}{part}{...}

  YAML options (in _quarto.yml):
    minitoc-newpage: false    # true → \newpage after each \minitoc
    chapter-openright: true   # false → \@openrightfalse (openany, digital version)
    pagestyle-sections: false # true → roman/arabic/Roman page numbering per section

  pagestyle-sections logic:
    - Chapters with .toc-black (acknowledgements, abstracts, lists) are front matter
      → lowercase roman numbering.
    - The first chapter WITHOUT .toc-black (e.g. Introduction, or first numbered
      chapter) marks the start of the main body → \mainmatter (arabic, reset to 1).
    - The appendices section marks the start of back matter → \pagenumbering{Roman}.

  TECHNICAL NOTE — Pandoc traversal order
  By default, Pandoc Lua filters are bottom-up: leaves (Header) are visited before
  the root (Meta). To ensure Meta is read before Header, two chained passes are used:
  pass1 reads Meta, pass2 processes Headers.

  TECHNICAL NOTE — glossary
  Entries {{< acr >}} / {{< terme >}} are handled entirely by shortcodes.lua, which
  writes _glossaire-entries.tex to disk. template.tex reads that file via
  \IfFileExists in the preamble. This filter is not involved in that mechanism
  because extension filters run BEFORE Quarto expands shortcodes — the Spans are
  therefore not yet present in the AST when this filter executes.
--]]

-- Identifiers of synthetic book sections generated by Quarto.
local QUARTO_BOOK_SECTIONS = {
  annexes    = true,   -- fr
  appendices = true,   -- en
}

-- IETF language tag → babel option name
local BABEL_LANG = {
  fr          = "french",
  en          = "english",
  ["en-US"]   = "american",
  ["en-GB"]   = "british",
  de          = "german",
  es          = "spanish",
  it          = "italian",
  pt          = "portuguese",
  nl          = "dutch",
}

-- Structural chapter titles to translate based on thesis-lang.
-- Only covers template-provided sections, not user content.
local CHAPTER_TRANSLATIONS = {
  en = {
    ["Bibliographie"]       = "Bibliography",
    ["Liste des acronymes"] = "List of Acronyms",
    ["Glossaire"]           = "Glossary",
  },
}

-- Options read from document metadata
local thesis_lang_val    = "fr"   -- set by pass1, used by pass2
local minitoc_newpage    = false
local chapter_openright  = true   -- default: openright (double-sided printing)
local pagestyle_sections = false  -- differentiated page numbering per section

-- State for the front matter → main matter transition (pagestyle-sections).
-- Triggered on the first chapter WITHOUT .toc-black (including Introduction).
local mainmatter_started = false

-- Robustly reads a YAML boolean (MetaBool or "true"/"false" string).
local function read_bool(v, default)
  if v == nil then return default end
  if type(v) == "boolean" then return v end
  local s = pandoc.utils.stringify(v)
  return s == "true" or s == "yes"
end

-- Converts a list of Pandoc inlines to LaTeX, preserving formatting
-- (bold, italic, math, etc.). Used for the long title in manually generated
-- \chapter[short]{long} and \section[short]{long} commands.
local function inlines_to_latex(inlines)
  local doc = pandoc.Pandoc({ pandoc.Plain(inlines) })
  return pandoc.write(doc, "latex"):gsub("%s+$", "")
end

-- Pass 1: read metadata and optionally inject into header-includes
local pass1 = {
  Meta = function(meta)
    minitoc_newpage    = read_bool(meta["minitoc-newpage"],    false)
    chapter_openright  = read_bool(meta["chapter-openright"],  true)
    pagestyle_sections = read_bool(meta["pagestyle-sections"], false)

    -- thesis-lang: derive babel-lang and babel-is-french.
    -- When thesis-lang != "fr", reset Quarto's French language overrides
    -- (crossref-tbl-title etc.) so they switch to English.
    local thesis_lang = meta["thesis-lang"]
      and pandoc.utils.stringify(meta["thesis-lang"]) or "fr"
    meta["babel-lang"]      = BABEL_LANG[thesis_lang] or "french"
    meta["babel-is-french"] = pandoc.MetaBool(thesis_lang == "fr")
    thesis_lang_val = thesis_lang  -- accessible from pass2
    if thesis_lang ~= "fr" then
      local lm = meta["language"] or pandoc.MetaMap({})
      lm["crossref-tbl-title"] = "Table"
      lm["crossref-lot-title"] = "List of Tables"
      lm["crossref-lof-title"] = "List of Figures"
      meta["language"] = lm
    end

    -- Inject <meta name="thesis-author"> on every HTML page so header-setup.html
    -- can read the author name regardless of which chapter is being viewed.
    -- Quarto only emits <meta name="author"> on index.html; this covers all pages.
    -- In a Quarto book, individual chapters receive author via meta["author"] on the
    -- root page but via meta["book"]["author"] on chapter pages — try both.
    if FORMAT:match("html") then
      local author_str = ""
      if meta["author"] then
        author_str = pandoc.utils.stringify(meta["author"])
      elseif meta["book"] and meta["book"]["author"] then
        author_str = pandoc.utils.stringify(meta["book"]["author"])
      end
      local hi = meta["header-includes"]
      if not hi then hi = pandoc.List() end
      -- Inject thesis-author on every page (Quarto only emits <meta name="author">
      -- on index.html; chapter pages need this custom tag).
      if author_str ~= "" then
        local tag = pandoc.RawBlock("html",
          '<meta name="thesis-author" content="' .. author_str .. '">')
        hi:insert(pandoc.MetaBlocks({ tag }))
      end
      -- Inject thesis-lang so header-setup.html can localise the topbar label
      -- ("Thèse de doctorat" vs "PhD Thesis") on every page.
      local tag_lang = pandoc.RawBlock("html",
        '<meta name="thesis-lang" content="' .. thesis_lang_val .. '">')
      hi:insert(pandoc.MetaBlocks({ tag_lang }))
      -- Optional: inject header-prefix to override the default topbar prefix entirely.
      -- Set via `header-prefix: "..."` in _quarto.yml (e.g. for a GitHub Pages doc branch).
      if meta["header-prefix"] then
        local prefix_str = pandoc.utils.stringify(meta["header-prefix"])
        local tag_prefix = pandoc.RawBlock("html",
          '<meta name="header-prefix" content="' .. prefix_str .. '">')
        hi:insert(pandoc.MetaBlocks({ tag_prefix }))
      end
      meta["header-includes"] = hi
    end

    -- If chapter-openright: false, disable the openright option of the book class.
    -- Inject \@openrightfalse into header-includes (executed in the preamble).
    if FORMAT == "latex" and not chapter_openright then
      local cmd = pandoc.RawBlock("latex",
        "\\makeatletter\\@openrightfalse\\makeatother")
      local hi = meta["header-includes"]
      if not hi then
        hi = pandoc.List()
      end
      hi:insert(pandoc.MetaBlocks({ cmd }))
      meta["header-includes"] = hi
    end

    return meta
  end
}

-- Pass 2: inject LaTeX commands into chapter headings
local pass2 = {
  Header = function(el)
    if FORMAT ~= "latex" then return el end

    -- ── Levels 2-4: sections, subsections, subsubsections ────────────────────
    -- Pandoc 3.x ignores short-title in its native LaTeX output.
    -- Generate \section[short]{long}\label{id} when short-title is present.
    -- Without short-title → let Pandoc handle it normally (return el).
    if el.level >= 2 then
      local short = el.attr.attributes["short-title"]
      if not short then return el end

      -- LaTeX command for the heading level (section, subsection, subsubsection, paragraph)
      local cmds = { "section", "subsection", "subsubsection", "paragraph" }
      local cmd  = cmds[el.level - 1] or "paragraph"
      local is_unnumbered = el.classes:includes("unnumbered")
      if is_unnumbered then cmd = cmd .. "*" end

      -- Long title with preserved formatting (pandoc.write → proper LaTeX)
      local title_latex = inlines_to_latex(el.content)
      local label = el.attr.identifier ~= ""
        and ("\\label{" .. el.attr.identifier .. "}") or ""

      if is_unnumbered then
        -- Starred forms (\section*) have no optional argument;
        -- emit the command without a short title.
        return pandoc.RawBlock("latex",
          string.format("\\%s{%s}%s", cmd, title_latex, label))
      else
        return pandoc.RawBlock("latex",
          string.format("\\%s[%s]{%s}%s", cmd, short, title_latex, label))
      end
    end

    -- ── Level 1 (chapters) ────────────────────────────────────────────────────
    local title = pandoc.utils.stringify(el.content)

    -- Skip empty-title chapters (Quarto stub for index.qmd)
    if title == "" then return {} end

    -- Skip HTML-only headings (index.qmd cover, tables.qmd, glossaire-entries.qmd).
    -- These files use {.content-visible when-format="html"} around their headings,
    -- but the Lua filter runs before Quarto's conditional-visibility filter, so the
    -- Header node is still visible here. The .no-latex class is the escape hatch:
    -- return nothing for LaTeX so no ghost \chapter* is generated.
    -- HTML output: heading passes through normally → appears in sidebar navigation.
    if el.classes:includes("no-latex") then return {} end

    -- Translate structural template titles based on thesis-lang
    -- (e.g. "Bibliographie" → "Bibliography" when thesis-lang: en)
    local ch_trans = CHAPTER_TRANSLATIONS[thesis_lang_val]
    if ch_trans and ch_trans[title] then
      title = ch_trans[title]
      el.content = { pandoc.Str(title) }
    end

    local is_toc_black = el.classes:includes("toc-black")
    local blocks = pandoc.List()

    if el.classes:includes("unnumbered") then
      -- Synthetic book sections (Annexes / Appendices) — Quarto handles them.
      -- If pagestyle-sections: true, inject the main matter → appendices transition here.
      --
      -- Critical sequence for capturing the correct page total of the main body:
      --
      --   \label{mainmatter:end}
      --       → deferred write: resolved at shipout of the current page.
      --         Since \clearpage fires BEFORE \pagenumbering{Roman}, the page
      --         is shipped out still in arabic numbering → label = N (correct).
      --
      --   \clearpage
      --       → ships out the last page of the main body (still arabic).
      --         After this we are on a fresh blank page.
      --
      --   \appendixmattertrue
      --       → switches the footer to uppercase Roman format.
      --
      --   \pagenumbering{Roman}
      --       → resets the counter to I (too late to pollute \label).
      --
      -- NOTE: without \clearpage, \pagenumbering{Roman} executes BEFORE the
      -- shipout of the last main-body page, and \label records "I" instead of N.
      if QUARTO_BOOK_SECTIONS[el.identifier] then
        if FORMAT == "latex" and pagestyle_sections then
          local inject = pandoc.RawBlock("latex",
            "\\label{mainmatter:end}\\clearpage\\appendixmattertrue\\pagenumbering{Roman}")
          return { inject, el }
        end
        return el
      end

      -- pagestyle-sections: front matter → main matter transition on the first
      -- chapter without .toc-black (= Introduction or first content chapter).
      -- \label{frontmatter:end} captures the last roman page number before the reset.
      if pagestyle_sections and not mainmatter_started and not is_toc_black then
        mainmatter_started = true
        blocks:insert(pandoc.RawBlock("latex",
          "\\label{frontmatter:end}\\mainmatter\\mainmattertrue"))
      end

      -- Ensure .unlisted to prevent a duplicate \addcontentsline
      -- (Pandoc adds one automatically for .unnumbered without .unlisted)
      if not el.classes:includes("unlisted") then
        el.classes:insert("unlisted")
      end

      -- Optional short title (short-title="…" attribute on the Markdown header).
      -- For \chapter*, there is no optional LaTeX argument → inject into
      -- \addcontentsline (TOC) and \markboth (running header) instead.
      local short_title = el.attr.attributes["short-title"] or title

      -- .toc-black → "frontchap" entry (black); otherwise "chapter" (red)
      local toc_type = is_toc_black and "frontchap" or "chapter"
      -- \markboth{title}{}: binding side = chapter title, outer side = empty.
      -- An unnumbered chapter has no sections in the header → empty rightmark
      -- avoids displaying the same title on both sides of recto/verso pages.
      --
      -- \adjustmtc only for "chapter"-type entries: \dominitoc builds one minitoc
      -- slot per \contentsline{chapter}{…} in the .toc file — it ignores
      -- "frontchap" entries entirely. Emitting \adjustmtc for frontchap chapters
      -- advances the mtc counter past non-existent slots and causes \minitoc to
      -- read the wrong .mtcN file in the numbered chapters that follow.
      -- \adjustmtc uniquement pour les entrées "chapter" : \dominitoc crée un slot
      -- par \contentsline{chapter}{…} dans le .toc — les entrées "frontchap" sont
      -- ignorées. Appeler \adjustmtc pour un frontchap avance le compteur mtc sur
      -- des slots inexistants et fait lire la mauvaise .mtcN aux chapitres suivants.
      local adjust = (toc_type == "chapter") and "\n\\adjustmtc" or ""
      local latex = string.format(
        "\\phantomsection\n\\addcontentsline{toc}{%s}{%s}%s\n\\markboth{\\MakeUppercase{%s}}{}",
        toc_type, short_title, adjust, short_title
      )
      blocks:insert(el)
      blocks:insert(pandoc.RawBlock("latex", latex))
      return blocks

    else
      -- Numbered chapter.
      -- If pagestyle-sections: true and this is the first non-.toc-black chapter
      -- (numbered chapters cannot have .toc-black, but we keep the check for safety):
      -- trigger the front matter → main matter transition.
      if pagestyle_sections and not mainmatter_started then
        mainmatter_started = true
        blocks:insert(pandoc.RawBlock("latex",
          "\\label{frontmatter:end}\\mainmatter\\mainmattertrue"))
      end

      -- short-title="…": Pandoc 3.x does not natively generate \chapter[short]{long}.
      -- Replace el with raw LaTeX including the optional argument.
      -- \label is rebuilt from el.attr.identifier (identical to what Pandoc would
      -- have generated), ensuring cross-reference compatibility.
      local short = el.attr.attributes["short-title"]
      if short then
        local title_latex = inlines_to_latex(el.content)
        local label = el.attr.identifier ~= ""
          and ("\\label{" .. el.attr.identifier .. "}") or ""
        blocks:insert(pandoc.RawBlock("latex",
          string.format("\\chapter[%s]{%s}%s", short, title_latex, label)))
      else
        blocks:insert(el)
      end

      -- \minitoc + optional page break
      local minitoc_latex = minitoc_newpage and "\\minitoc\n\\newpage" or "\\minitoc"
      blocks:insert(pandoc.RawBlock("latex", minitoc_latex))
      return blocks
    end
  end
}

-- Pass 3: handle .render-demo divs + inject language label for styled code blocks.
--
-- .render-demo: a fenced div wrapping a "Rendu :" label + rendered example.
--   HTML → kept as-is (CSS adds border-top/border-bottom).
--   LaTeX → unwrapped; thin \rule injected before and after the content so
--           floats inside are free to move normally (no boxing). /
-- .render-demo : un div encadrant le label « Rendu : » et son contenu rendu.
--   HTML → conservé tel quel (CSS ajoute les bordures haut/bas).
--   LaTeX → dé-wrappé ; \rule fin injecté avant et après — les flottants
--           à l'intérieur restent libres de se déplacer (pas de boîte).
-- Emits \def\CodeBlockLangLabel{lang} as a RawBlock immediately before each
-- CodeBlock so that the Shaded tcolorbox in template.tex can display the
-- language name in its title bar. Empty string when no language is declared. /
-- Injecte \def\CodeBlockLangLabel{lang} avant chaque CodeBlock en LaTeX.
-- Vide si aucun langage n'est déclaré → Shaded sans bandeau titre.
local pass3 = {
  Div = function(el)
    if not el.classes:includes("render-demo") then return el end
    if FORMAT ~= "latex" then return el end
    -- Dashed rule in lilacode!65, using TikZ (loaded by mdframed with tikz framemethod).
    -- \tikz inline form keeps it as a paragraph element so floats inside are free. /
    -- Règle pointillée lilacode!65 via TikZ. Forme inline \tikz → les flottants restent libres.
    local rule_tex =
      "\\vspace{4pt}\\noindent" ..
      "\\tikz[baseline=-0.5ex]{" ..
      "\\draw[color=lilacode!65,line width=0.6pt,dash pattern=on 4pt off 3pt]" ..
      "(0,0)--(\\linewidth,0);" ..
      "}\\vspace{4pt}"
    local top_rule = pandoc.RawBlock("latex", rule_tex)
    local bot_rule = pandoc.RawBlock("latex", rule_tex)
    -- Color the "Rendu :" label (first Strong in the first Para) in lilacode,
    -- without coloring any inline rendered text that may follow on the same line. /
    -- Colore uniquement le premier Strong (label « Rendu : ») en lilacode,
    -- sans toucher au texte rendu inline qui peut suivre sur la même ligne.
    local content = el.content
    if content[1] and content[1].t == "Para" then
      local para = content[1]
      local new_inlines = pandoc.List()
      local colored = false
      for _, inline in ipairs(para.content) do
        if not colored and inline.t == "Strong" then
          colored = true
          new_inlines:insert(pandoc.RawInline("latex", "\\textcolor{lilacode}{"))
          new_inlines:insert(inline)
          new_inlines:insert(pandoc.RawInline("latex", "}"))
        else
          new_inlines:insert(inline)
        end
      end
      para.content = new_inlines
      content[1] = para
    end
    -- Wrap everything in adjustwidth so the block (rules + content) is narrower
    -- than the surrounding text. \linewidth inside adjustwidth is updated, so the
    -- TikZ rules automatically narrow to match. Floats placed with [H] will still
    -- span the full text width (LaTeX float mechanics ignore list indentation). /
    -- adjustwidth rétrécit l'ensemble (filets + contenu) ; \linewidth est mis à jour
    -- donc les filets TikZ s'adaptent. Les flottants [H] gardent la pleine largeur.
    local adj_begin = pandoc.RawBlock("latex",
      "\\begin{adjustwidth}{1.2cm}{1.2cm}")
    local adj_end   = pandoc.RawBlock("latex", "\\end{adjustwidth}")
    local blocks = pandoc.List({ adj_begin, top_rule })
    for _, b in ipairs(content) do blocks:insert(b) end
    blocks:insert(bot_rule)
    blocks:insert(adj_end)
    return blocks
  end,

  CodeBlock = function(el)
    if FORMAT ~= "latex" then return el end
    -- Skip internal Quarto classes (quarto-*); they produce no Shaded block. /
    -- Ignore les classes internes Quarto (quarto-*) ; elles ne produisent pas de Shaded.
    local raw = el.classes[1] or ""
    if raw:match("^quarto%-") then raw = "" end
    -- Keep only safe characters for a \def argument (letters, digits, hyphen, plus). /
    -- Conserve uniquement les caractères sûrs pour un argument \def.
    local lang = raw:gsub("[^%a%d%-%+]", "")
    return {
      pandoc.RawBlock("latex", "\\def\\CodeBlockLangLabel{" .. lang .. "}"),
      el
    }
  end
}

return { pass1, pass2, pass3 }
