--[[
  shortcodes.lua — Quarto shortcodes for the glossary and acronyms

  ── Declaration shortcodes ────────────────────────────────────────────────────

    {{< acr   label ABBR "Full form" >}}
    {{< terme label "term" "Definition" >}}

  All definitions must be placed in a single frontmatter glossary file
  (e.g. content_fr/liminaire/glossaire-entries.qmd).

  ── Reference shortcodes ──────────────────────────────────────────────────────

    {{< gls  label >}}   →  \gls{label}         first use: full form (ABBR);
                                                  subsequent uses: ABBR
    {{< acrs label >}}   →  \acrshort{label}     always the abbreviation
    {{< acrl label >}}   →  \acrlong{label}      always the full form
    {{< acrf label >}}   →  \acrfull{label}      full form (ABBR) — complete form

  In HTML output, reference shortcodes display plain text (no glossaries markup)
  using the gloss_lookup table built at declaration time.

  ── Mechanism (declaration) ───────────────────────────────────────────────────

  The {{< acr >}} / {{< terme >}} shortcodes maintain an in-memory list
  (gloss_entries) and rewrite _glossaire-entries.tex on every call (mode "w"
  = overwrite with accumulated content). template.tex reads this file via
  \IfFileExists in the preamble, after \makenoidxglossaries.

  CONSTRAINT: all definitions must be in a single .qmd file. If Quarto uses
  separate Lua instances per file, entries from file N would overwrite those
  from file N-1. The gloss_labels deduplication set prevents duplicate entries
  when Quarto scans multiple glossary-entries.qmd files across profiles.
--]]

-- ── Shared state ──────────────────────────────────────────────────────────────

-- List of LaTeX commands to write to _glossaire-entries.tex
local gloss_entries = {}

-- Set of already-registered labels — prevents duplicates when Quarto
-- instantiates the filter separately for content_fr/ and content_en/
-- during a multi-profile render (each instance would otherwise write
-- the same entries).
local gloss_labels = {}

-- Lookup table: label → data (for HTML rendering of reference shortcodes
-- {{< gls >}} / {{< acrs >}} / {{< acrl >}} / {{< acrf >}})
local gloss_lookup = {}

local GLOSS_FILE      = "_glossaire-entries.tex"
-- Pre-rendered HTML tables written alongside the .tex file so that
-- {{< gloss-html >}} can read them from a different Lua instance
-- (Quarto creates one instance per chapter file in a book render).
-- Tableaux HTML pré-rendus écrits en même temps que le .tex afin que
-- {{< gloss-html >}} puisse les lire depuis une autre instance Lua.
local GLOSS_ACR_HTML  = "_gloss-acr.html"
local GLOSS_MAIN_HTML = "_gloss-main.html"

-- Rewrites the entire file with all entries accumulated so far.
local function write_gloss_file()
  local f = io.open(GLOSS_FILE, "w")
  if not f then
    quarto.log.warning("Cannot write " .. GLOSS_FILE ..
      " — glossary definitions will not be available.")
    return
  end
  f:write("% Auto-generated by shortcodes.lua — do not edit.\n")
  for _, entry in ipairs(gloss_entries) do
    f:write(entry .. "\n")
  end
  f:close()
end

-- Writes sorted HTML table files for acronyms and glossary terms.
-- Called after every {{< acr >}} / {{< terme >}} declaration so that the files
-- always reflect the current state of gloss_lookup.
-- Écrit les tableaux HTML triés. Appelé après chaque {{< acr >}} / {{< terme >}}.
local function write_html_gloss_files()
  local acr_entries  = {}
  local term_entries = {}
  for _, data in pairs(gloss_lookup) do
    if data.type == "acr" then
      table.insert(acr_entries, data)
    else
      table.insert(term_entries, data)
    end
  end
  table.sort(acr_entries,  function(a, b) return a.sigle:lower() < b.sigle:lower() end)
  table.sort(term_entries, function(a, b) return a.mot:lower()   < b.mot:lower()   end)

  local function write_table(filename, entries, key_fn, val_fn)
    local f = io.open(filename, "w")
    if not f then return end
    if #entries > 0 then
      f:write('<table class="gloss-table"><tbody>\n')
      for _, d in ipairs(entries) do
        f:write("  <tr><td><strong>" .. key_fn(d) .. "</strong></td>" ..
                "<td>" .. val_fn(d) .. "</td></tr>\n")
      end
      f:write("</tbody></table>\n")
    end
    f:close()
  end

  write_table(GLOSS_ACR_HTML,  acr_entries,
    function(d) return d.sigle end, function(d) return d.dev end)
  write_table(GLOSS_MAIN_HTML, term_entries,
    function(d) return d.mot end,   function(d) return d.def end)
end

-- ── Declaration shortcodes ────────────────────────────────────────────────────

-- {{< acr label ABBR "Full form" >}}
local function acr(args, kwargs, meta)
  if #args < 3 then
    quarto.log.warning(
      "Shortcode 'acr': 3 arguments required — label, ABBR, \"Full form\".\n" ..
      "Example: {{< acr ai AI \"artificial intelligence\" >}}")
    return pandoc.List()
  end
  local label = pandoc.utils.stringify(args[1])
  local sigle = pandoc.utils.stringify(args[2])
  local dev   = pandoc.utils.stringify(args[3])
  if label ~= "" and not gloss_labels[label] then
    gloss_labels[label] = true
    table.insert(gloss_entries,
      string.format("\\newacronym{%s}{%s}{%s}", label, sigle, dev))
    gloss_lookup[label] = { type = "acr", sigle = sigle, dev = dev }
    write_gloss_file()
    write_html_gloss_files()
  end
  return pandoc.List()
end

-- {{< terme label "word" "Definition" >}}
local function terme(args, kwargs, meta)
  if #args < 3 then
    quarto.log.warning(
      "Shortcode 'terme': 3 arguments required — label, \"word\", \"Definition\".\n" ..
      "Example: {{< terme ontology \"ontology\" \"Formal representation of knowledge...\" >}}")
    return pandoc.List()
  end
  local label = pandoc.utils.stringify(args[1])
  local mot   = pandoc.utils.stringify(args[2])
  local def   = pandoc.utils.stringify(args[3])
  if label ~= "" and not gloss_labels[label] then
    gloss_labels[label] = true
    table.insert(gloss_entries,
      string.format("\\newglossaryentry{%s}{name={%s},description={%s}}",
        label, mot, def))
    gloss_lookup[label] = { type = "terme", mot = mot, def = def }
    write_gloss_file()
    write_html_gloss_files()
  end
  return pandoc.List()
end

-- ── Reference shortcodes ──────────────────────────────────────────────────────

-- Returns a LaTeX RawInline or plain text for HTML.
local function raw_or_text(latex_cmd, html_text)
  if FORMAT == "latex" then
    return pandoc.RawInline("latex", latex_cmd)
  else
    return pandoc.Str(html_text)
  end
end

-- Returns HTML display text based on entry type and requested form.
-- form: "sigle" | "dev" | "full" | "auto" (= "full" for the first reference)
local function html_text(label, forme)
  local e = gloss_lookup[label]
  if not e then return label end   -- unknown label → display as-is
  if e.type == "acr" then
    if forme == "sigle" then return e.sigle
    elseif forme == "dev"  then return e.dev
    else return e.dev .. "\u{00A0}(" .. e.sigle .. ")"   -- full
    end
  else  -- terme
    if forme == "sigle" then return e.mot
    elseif forme == "dev"  then return e.def
    else return e.mot
    end
  end
end

-- {{< gls label >}}
-- PDF: \gls{label}   HTML: full form (ABBR) for an acronym, word for a term
local function gls(args, kwargs, meta)
  if #args < 1 then return pandoc.Str("") end
  local label = pandoc.utils.stringify(args[1])
  return raw_or_text("\\gls{" .. label .. "}", html_text(label, "full"))
end

-- {{< acrs label >}}  →  abbreviation
local function acrs(args, kwargs, meta)
  if #args < 1 then return pandoc.Str("") end
  local label = pandoc.utils.stringify(args[1])
  return raw_or_text("\\acrshort{" .. label .. "}", html_text(label, "sigle"))
end

-- {{< acrl label >}}  →  full form
local function acrl(args, kwargs, meta)
  if #args < 1 then return pandoc.Str("") end
  local label = pandoc.utils.stringify(args[1])
  return raw_or_text("\\acrlong{" .. label .. "}", html_text(label, "dev"))
end

-- {{< acrf label >}}  →  full form (ABBR)
local function acrf(args, kwargs, meta)
  if #args < 1 then return pandoc.Str("") end
  local label = pandoc.utils.stringify(args[1])
  return raw_or_text("\\acrfull{" .. label .. "}", html_text(label, "full"))
end

-- {{< jury-html >}}
-- PDF: returns nothing — jury is rendered by before-body.tex
-- HTML: generates a <table class="jury-table"> from the meta.jury YAML list
--       Jury HTML / Tableau du jury (HTML uniquement)
local function jury_html(args, kwargs, meta)
  if FORMAT == "latex" then
    return pandoc.List()
  end
  local rows = {}
  if meta and meta.jury then
    for _, member in ipairs(meta.jury) do
      local nom   = pandoc.utils.stringify(member.nom   or "")
      local titre = pandoc.utils.stringify(member.titre or "")
      local role  = pandoc.utils.stringify(member.role  or "")
      table.insert(rows,
        "  <tr>" ..
        "<td><strong>" .. nom   .. "</strong></td>" ..
        "<td>"         .. titre .. "</td>" ..
        "<td><em>"     .. role  .. "</em></td>" ..
        "</tr>")
    end
  end
  if #rows == 0 then
    return pandoc.RawBlock("html",
      "<!-- jury-html: no jury entries found in metadata -->")
  end
  local html = '<table class="jury-table"><tbody>\n' ..
    table.concat(rows, "\n") .. "\n</tbody></table>"
  return pandoc.RawBlock("html", html)
end

-- ── Accent-stripping map for PDF filename slug computation ────────────────────
-- Mirrors the Python unicodedata.normalize('NFD') + encode('ascii','ignore')
-- approach used in postrender.sh to derive the author slug for the PDF filename.
-- Reproduit la normalisation NFD Python de postrender.sh pour le slug auteur.
local ACCENT_MAP = {
  ["à"]="a",["â"]="a",["ä"]="a",["á"]="a",["ã"]="a",["å"]="a",
  ["è"]="e",["é"]="e",["ê"]="e",["ë"]="e",
  ["ì"]="i",["î"]="i",["ï"]="i",["í"]="i",
  ["ò"]="o",["ó"]="o",["ô"]="o",["ö"]="o",["õ"]="o",
  ["ù"]="u",["ú"]="u",["û"]="u",["ü"]="u",
  ["ç"]="c",["ñ"]="n",["ÿ"]="y",["æ"]="ae",["œ"]="oe",
  ["À"]="a",["Â"]="a",["Ä"]="a",["Á"]="a",["Ã"]="a",
  ["È"]="e",["É"]="e",["Ê"]="e",["Ë"]="e",
  ["Î"]="i",["Ï"]="i",["Í"]="i",["Ì"]="i",
  ["Ô"]="o",["Ö"]="o",["Ó"]="o",["Ò"]="o",
  ["Û"]="u",["Ü"]="u",["Ú"]="u",["Ù"]="u",
  ["Ç"]="c",["Ñ"]="n",["Ÿ"]="y",["Æ"]="ae",["Œ"]="oe",
}

-- Converts an author name to a filesystem-safe slug.
-- Mirrors postrender.sh: NFD normalization → lowercase → spaces/hyphens → underscores.
-- Convertit un nom d'auteur en slug compatible avec le système de fichiers.
local function slugify_author(s)
  for accent, replacement in pairs(ACCENT_MAP) do
    s = s:gsub(accent, replacement)
  end
  s = s:lower()
  s = s:gsub("[ \t%-]", "_")
  s = s:gsub("'", "_")
  s = s:gsub("[^%a%d_]", "")
  s = s:gsub("_+", "_")
  s = s:gsub("^_+", ""):gsub("_+$", "")
  return s
end

-- {{< cnam-logos >}}
-- PDF: returns nothing (logos are embedded in before-body.tex).
-- HTML: renders the Cnam logo. Shows co-institution logo when cotutelle: true.
--       HTML : barre de logos Cnam. Logo co-tutelle si cotutelle: true.
local function cnam_logos(args, kwargs, meta)
  if FORMAT == "latex" then return pandoc.List() end
  local cotutelle = false
  if meta and meta.cotutelle then
    local v = meta.cotutelle
    cotutelle = (type(v) == "boolean" and v)
             or (type(v) ~= "boolean" and pandoc.utils.stringify(v) == "true")
  end
  local html = '<div class="cnam-logo-bar">\n' ..
    '  <img src="images/Cnam.jpg" alt="Logo du Cnam" class="cnam-logo">\n'
  if cotutelle then
    html = html ..
      '  <img src="images/logo_cotut_codirec_latex.jpg"' ..
      ' alt="Logo co-tutelle" class="cotut-logo">\n'
  end
  html = html .. '</div>'
  return pandoc.RawBlock("html", html)
end

-- {{< gloss-html [type] >}}
-- type: "acronym" → acronym entries (acr); "main" → glossary terms (terme).
-- Omitting type lists all entries. HTML only; PDF returns nothing.
-- Génère un tableau HTML. PDF : rien (\printnoidxglossary le gère).
--
-- Strategy: Quarto creates a separate Lua instance per chapter file in a book render.
-- gloss_lookup is populated when glossaire-entries.qmd is processed. When acronymes.qmd
-- or glossaire.qmd is processed (later, different instance), gloss_lookup is empty.
-- Fallback: read the HTML tables pre-written by write_html_gloss_files() to disk.
--
-- Stratégie : Quarto crée une instance Lua par chapitre. gloss_lookup est alimenté lors du
-- traitement de glossaire-entries.qmd. Dans les chapitres suivants (autre instance),
-- gloss_lookup est vide → lecture des fichiers HTML pré-écrits par write_html_gloss_files().
local function gloss_html(args, kwargs, meta)
  if FORMAT == "latex" then return pandoc.List() end
  local filter_type = #args > 0 and pandoc.utils.stringify(args[1]) or nil

  -- ── Path A: same Lua instance — gloss_lookup is populated ────────────────
  if next(gloss_lookup) ~= nil then
    local entries = {}
    for label, data in pairs(gloss_lookup) do
      if filter_type == nil
        or (filter_type == "acronym" and data.type == "acr")
        or (filter_type == "main"    and data.type == "terme") then
        table.insert(entries, { label = label, data = data })
      end
    end
    table.sort(entries, function(a, b)
      local ka = a.data.type == "acr" and a.data.sigle or a.data.mot
      local kb = b.data.type == "acr" and b.data.sigle or b.data.mot
      return ka:lower() < kb:lower()
    end)
    local rows = {}
    for _, entry in ipairs(entries) do
      local d = entry.data
      if d.type == "acr" then
        table.insert(rows, "  <tr><td><strong>" .. d.sigle ..
          "</strong></td><td>" .. d.dev .. "</td></tr>")
      else
        table.insert(rows, "  <tr><td><strong>" .. d.mot ..
          "</strong></td><td>" .. d.def .. "</td></tr>")
      end
    end
    if #rows == 0 then
      return pandoc.RawBlock("html", "<p><em>No matching entries.</em></p>")
    end
    return pandoc.RawBlock("html",
      '<table class="gloss-table"><tbody>\n' ..
      table.concat(rows, "\n") .. "\n</tbody></table>")
  end

  -- ── Path B: different Lua instance — read from pre-written HTML file ─────
  local filename = (filter_type == "acronym") and GLOSS_ACR_HTML
                or (filter_type == "main")    and GLOSS_MAIN_HTML
                or GLOSS_ACR_HTML  -- default fallback
  local f = io.open(filename, "r")
  if not f then
    return pandoc.RawBlock("html",
      '<p><em>No glossary data found — render the full book first: ' ..
      '<code>quarto render --profile fr</code>.<br>' ..
      'Données de glossaire absentes — lancer d\'abord : ' ..
      '<code>quarto render --profile fr</code>.</em></p>')
  end
  local content = f:read("*a")
  f:close()
  if content == "" then
    return pandoc.RawBlock("html", "<p><em>No entries defined.</em></p>")
  end
  return pandoc.RawBlock("html", content)
end

-- {{< pdf-link >}}
-- PDF: returns nothing.
-- HTML: download button linking to the renamed PDF (output-file + author slug),
--       computed using the same algorithm as postrender.sh.
--       Bouton de téléchargement du PDF (même convention de nommage que postrender.sh).
local function pdf_link(args, kwargs, meta)
  if FORMAT == "latex" then return pandoc.List() end

  -- output-file basename (e.g. "these_fr") / nom de base du fichier de sortie
  local output_file = ""
  if meta and meta.book and meta.book["output-file"] then
    output_file = pandoc.utils.stringify(meta.book["output-file"])
  end

  -- author name for slug computation / nom de l'auteur pour le slug
  local author = ""
  if meta and meta.book and meta.book.author then
    author = pandoc.utils.stringify(meta.book.author)
  elseif meta and meta.author then
    author = pandoc.utils.stringify(meta.author)
  end

  local slug    = slugify_author(author)
  local pdf_name = slug ~= "" and (output_file .. "_" .. slug .. ".pdf")
                               or (output_file .. ".pdf")

  -- Label adapts to thesis language / Libellé selon la langue de la thèse
  local lang  = (meta and meta["thesis-lang"])
    and pandoc.utils.stringify(meta["thesis-lang"]) or "fr"
  local label = lang == "fr" and "T&#233;l&#233;charger le PDF" or "Download PDF"

  local html = '<a href="' .. pdf_name ..
    '" class="pdf-download-btn" download>&#8659;&nbsp;' .. label .. '</a>'
  return pandoc.RawInline("html", html)
end

return {
  ["acr"]        = acr,
  ["terme"]      = terme,
  ["gls"]        = gls,
  ["acrs"]       = acrs,
  ["acrl"]       = acrl,
  ["acrf"]       = acrf,
  ["jury-html"]  = jury_html,
  ["cnam-logos"] = cnam_logos,
  ["gloss-html"] = gloss_html,
  ["pdf-link"]   = pdf_link,
}
