#!/bin/bash
# Post-render: clean LaTeX build artifacts and rename PDF and .tex output files.
# Usage: ./postrender.sh <lang> <output-dir> [pdfa]
#   pdfa  (optional) — run Ghostscript PDF/A-1b conversion after rendering.
#                      Use only for the final submission to theses.fr.
#                      Requires Ghostscript: brew install ghostscript (macOS)
#                                            apt install ghostscript  (Linux)
# Called via post-render in _quarto-fr.yml / _quarto-en.yml.

LANG="$1"
OUTPUT_DIR="$2"
PDFA_MODE="$3"   # optional: "pdfa" to enable Ghostscript conversion

if [ -z "$LANG" ] || [ -z "$OUTPUT_DIR" ]; then
  echo "postrender.sh: usage: postrender.sh <lang> <output-dir> [pdfa]" >&2
  exit 1
fi

# ── Remove spurious directories copied by Quarto's resource scanner ──────────
# Quarto copies all root-level directories to the output dir when it mirrors the
# project structure for HTML books. _reference/ (archival sources) and the other
# profile's output dir (_thesis/ or _thesis-en/) are never needed in the output.
# Quarto copie tous les dossiers de la racine dans le dossier de sortie HTML.
# _reference/ et le dossier de sortie de l'autre profil sont inutiles en sortie.
rm -rf "${OUTPUT_DIR}/_reference"
rm -rf "${OUTPUT_DIR}/_these_fr"
rm -rf "${OUTPUT_DIR}/_thesis-en"

# ── Clean LaTeX build artifacts ───────────────────────────────────────────────

rm -f \
  *.aux *.log \
  *.maf *.mtc *.mtc[0-9] *.mtc[0-9][0-9] \
  *.toc *.lof *.lot \
  *.blg *.bbl \
  *.idx *.ilg *.ind \
  *.out \
  pdfa.xmpi *.xmpdata \
  _glossaire-entries.tex \
  _gloss-acr.html _gloss-main.html   # HTML glossary tables generated by shortcodes.lua

# ── Rename these_<lang>.pdf/.tex → these_<lang>_<author>.pdf/.tex ─────────────

AUTHOR=$(grep -m1 'author:' _quarto.yml \
  | sed 's/.*author:[[:space:]]*//' \
  | tr -d '"' \
  | tr -d "'")

if [ -z "$AUTHOR" ]; then
  exit 0
fi

AUTHOR_SLUG=$(printf '%s' "$AUTHOR" \
  | python3 -c "import unicodedata,sys; s=sys.stdin.read().strip(); print(unicodedata.normalize('NFD',s).encode('ascii','ignore').decode())" \
  | tr '[:upper:]' '[:lower:]' \
  | tr " \t-" '_' \
  | sed "s/'/_/g" \
  | sed 's/[^a-z0-9_]//g' \
  | sed 's/_\{2,\}/_/g; s/^_//; s/_$//')

if [ -z "$AUTHOR_SLUG" ]; then
  exit 0
fi

SRC_PDF="${OUTPUT_DIR}/these_${LANG}.pdf"
DST_PDF="${OUTPUT_DIR}/these_${LANG}_${AUTHOR_SLUG}.pdf"
SRC_TEX="these_${LANG}.tex"
DST_TEX="these_${LANG}_${AUTHOR_SLUG}.tex"

# Track whether a PDF was produced in this render.
# Déterminer si un PDF a été produit dans ce rendu.
PDF_GENERATED=false
if [ -f "$SRC_PDF" ]; then
  mv "$SRC_PDF" "$DST_PDF"
  PDF_GENERATED=true
  echo "PDF renamed: $DST_PDF"
  # Keep a copy under the canonical output-file name so Quarto's preview server can
  # stat it after the rename. Without this, `quarto preview` crashes with:
  #   NotFound: No such file or directory: stat '_these_<lang>/these_<lang>.pdf'
  # The copy is overwritten by pdflatex on every subsequent render and is gitignored
  # (the whole output directory is in .gitignore). /
  # Conserver une copie au nom canonique pour que le serveur de preview puisse la
  # retrouver après le renommage. Écrasée à chaque re-rendu. Gitignorée.
  cp -p "$DST_PDF" "$SRC_PDF"
fi

# Fix HTML navigation links and update the PDF download link.
#
# Two render scenarios:
#
# A) Full render (PDF_GENERATED=true):
#    Quarto emits .pdf extensions for ALL book navigation hrefs in HTML pages
#    (cross-format artefact). Two-pass fix per file:
#      Pass 1 — all relative .pdf hrefs → .html  (navigation links)
#      Pass 2 — these_<lang>.html → these_<lang>_<slug>.pdf  (download link)
#
# B) HTML-only render (PDF_GENERATED=false):
#    Nav hrefs are already .html — running the two-pass sed would corrupt them
#    (pass 2 matches these_fr in other paths, double-slug risk on re-runs).
#    One targeted pass: these_<lang>.pdf → these_<lang>_<slug>.pdf  (download only).
#    Pattern anchors on the exact bare filename, so already-slugified hrefs are
#    never matched → safe to run multiple times.
#
# Deux scénarios de rendu :
# A) Rendu complet : Quarto génère des hrefs .pdf pour toute la navigation HTML.
#    Correction en deux passes.
# B) Rendu HTML seul : hrefs déjà .html. Une passe ciblée corrige uniquement le
#    lien de téléchargement these_<lang>.pdf → these_<lang>_<slug>.pdf.

# Detect BSD sed (macOS) vs GNU sed (Linux): BSD requires -i '' with empty string.
# Détecter BSD sed (macOS) vs GNU sed (Linux) : BSD requiert -i '' avec chaîne vide.
if sed --version >/dev/null 2>&1; then
  GNU_SED=true
else
  GNU_SED=false
fi

# Two-pass sed — runs for both full and HTML-only renders.
#
# Quarto always emits .pdf extensions for book navigation hrefs when both PDF and
# HTML formats are registered (full render AND --no-clean HTML-only re-render).
# Pass 1 — all relative .pdf hrefs → .html  (navigation links)
# Pass 2 — these_<lang>.html → these_<lang>_<slug>.pdf  (restore download link)
#
# Quarto génère toujours des hrefs .pdf pour la navigation book quand les deux
# formats sont enregistrés. Deux passes : navigation .pdf→.html, puis restauration
# du lien de téléchargement these_<lang>.html → these_<lang>_<slug>.pdf.
find "$OUTPUT_DIR" -name "*.html" | while IFS= read -r f; do
  if grep -q '\.pdf"' "$f" 2>/dev/null; then
    if [ "$GNU_SED" = true ]; then
      sed -i \
        -e "s|href=\"\([^:\"]*\)\.pdf\"|href=\"\1.html\"|g" \
        -e "s|href=\"\([^\"]*these_${LANG}\)\.html\"|href=\"\1_${AUTHOR_SLUG}.pdf\"|g" \
        "$f"
    else
      sed -i '' \
        -e "s|href=\"\([^:\"]*\)\.pdf\"|href=\"\1.html\"|g" \
        -e "s|href=\"\([^\"]*these_${LANG}\)\.html\"|href=\"\1_${AUTHOR_SLUG}.pdf\"|g" \
        "$f"
    fi
  fi
done
echo "HTML links updated → these_${LANG}_${AUTHOR_SLUG}.pdf"

if [ -f "$SRC_TEX" ]; then
  mv "$SRC_TEX" "$DST_TEX"
  echo "TeX renamed: $DST_TEX"
fi

# ── Generate cover image from PDF page 1 ──────────────────────────────────────
# Saves page 1 of the compiled PDF as images/cover.png for the HTML cover page.
# Enregistre la page 1 du PDF compilé en images/cover.png pour la couverture HTML.
# Requires poppler-utils (pdftoppm) or ImageMagick (convert + Ghostscript).
#   macOS:  brew install poppler      or  brew install imagemagick ghostscript
#   Linux:  apt install poppler-utils or  apt install imagemagick ghostscript
# Note: ImageMagick may need PDF permissions in /etc/ImageMagick-*/policy.xml.
# Only regenerated when a new PDF was produced; HTML-only renders reuse the
# existing cover.png (Quarto copies images/ to the output dir during render).
# Régénéré uniquement quand un nouveau PDF est produit ; les rendus HTML seuls
# réutilisent le cover.png existant (Quarto copie images/ en sortie).

if [ "$PDF_GENERATED" = true ] && [ -f "$DST_PDF" ]; then
  COVER_SRC="images/cover.png"
  COVER_DST="${OUTPUT_DIR}/images/cover.png"

  if command -v pdftoppm >/dev/null 2>&1; then
    # -singlefile: output <prefix>.png without page-number suffix.
    pdftoppm -r 150 -png -singlefile -f 1 -l 1 "$DST_PDF" "images/cover" \
      && echo "Cover image generated: images/cover.png"
  elif command -v convert >/dev/null 2>&1; then
    # [0] = first page (0-indexed); Ghostscript must also be installed.
    convert -density 150 "${DST_PDF}[0]" -quality 90 "$COVER_SRC" \
      && echo "Cover image generated: images/cover.png"
  else
    echo "postrender.sh: install 'poppler' (pdftoppm) or 'ImageMagick' (convert)" \
         "to auto-generate images/cover.png." >&2
  fi

  # Copy the freshly generated cover into the HTML output directory so that
  # index.html immediately shows the current version — not the one from the
  # previous render (Quarto copies resources before postrender runs).
  # Copier la couverture dans le dossier de sortie HTML pour que index.html
  # affiche immédiatement la version courante, et non celle du rendu précédent
  # (Quarto copie les ressources avant l'exécution du postrender).
  if [ -f "$COVER_SRC" ]; then
    mkdir -p "${OUTPUT_DIR}/images"
    cp "$COVER_SRC" "$COVER_DST" \
      && echo "Cover image copied to: $COVER_DST"
  fi
fi

# ── Optional: Ghostscript PDF/A-1b conversion ─────────────────────────────────
# Activated by passing "pdfa" as a third argument:
#   - ./_scripts/postrender.sh fr _these_fr pdfa     (in _quarto-fr.yml)
# Flattens transparency (§6.4) and fixes font metrics (§6.3.5/§6.3.6).
# Intended for the final submission to theses.fr — not needed for daily builds.
# Processing time: ~1–2 min depending on PDF size and number of figures.
# Activated en passant "pdfa" en troisième argument. Aplatit la transparence
# et corrige les métriques de polices. Uniquement pour la soumission finale.
if [ "$PDFA_MODE" = "pdfa" ] && [ "$PDF_GENERATED" = true ] && [ -f "$DST_PDF" ]; then
  GS_BIN=$(command -v gs 2>/dev/null)
  if [ -z "$GS_BIN" ]; then
    echo "postrender.sh: 'gs' (Ghostscript) not found — PDF/A conversion skipped." >&2
    echo "  macOS : brew install ghostscript" >&2
    echo "  Linux : apt install ghostscript   or   dnf install ghostscript" >&2
  else
    echo "Running Ghostscript PDF/A-1b conversion…"
    SIZE_BEFORE=$(wc -c < "$DST_PDF" | tr -d ' ')
    PDFA_TMP="${DST_PDF}.tmp"
    "$GS_BIN" \
      -dPDFA=1 \
      -dBATCH \
      -dNOPAUSE \
      -dNOOUTERSAVE \
      -dPDFACompatibilityPolicy=2 \
      -sColorConversionStrategy=UseDeviceIndependentColor \
      -sDEVICE=pdfwrite \
      -sOutputFile="$PDFA_TMP" \
      "$DST_PDF"
    GS_STATUS=$?
    if [ $GS_STATUS -eq 0 ] && [ -s "$PDFA_TMP" ]; then
      mv "$PDFA_TMP" "$DST_PDF"
      cp -p "$DST_PDF" "$SRC_PDF"   # keep canonical copy in sync
      SIZE_AFTER=$(wc -c < "$DST_PDF" | tr -d ' ')
      echo "PDF/A-1b conversion done: $((SIZE_BEFORE / 1024)) KB → $((SIZE_AFTER / 1024)) KB"
      echo "Validate on facile.cines.fr before submitting to theses.fr."
    else
      rm -f "$PDFA_TMP"
      echo "postrender.sh: Ghostscript conversion failed (exit $GS_STATUS) — original PDF preserved." >&2
    fi
  fi
fi
